# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('COACH', 'Coach'), ('PLAYER', 'Player'), ('SCOUT', 'Scout'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('country', models.CharField(choices=[('--', 'Unknown'), ('AL', 'Algeria'), ('AN', 'Angola'), ('BA', 'Bantu'), ('BE', 'Benin'), ('BT', 'Botswana'), ('BF', 'Burkina Faso (Upper Volta)'), ('BR', 'Burundi'), ('BU', 'Bushman'), ('BH', 'Bushongo'), ('CR', 'Cameroon'), ('CI', 'Canary Is.'), ('CV', 'Cape Verde'), ('CA', 'Central African Republic'), ('DH', 'Dahomean'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('ET', 'Ethiopia'), ('GB', 'Gabon'), ('GA', 'Gambia'), ('GH', 'Ghana'), ('GC', 'Gold Coast'), ('GU', 'Guinea'), ('HO', 'Hottentot'), ('IC', 'Ivory Coast'), ('KY', 'Kenya'), ('LE', 'Lesotho'), ('LI', 'Liberia'), ('LB', 'Libya'), ('MD', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MN', 'Mande'), ('MU', 'Mauritania'), ('MA', 'Mauritius'), ('MB', 'Mbundu'), ('ME', 'Mende'), ('MR', 'Morocco'), ('MZ', 'Mozambique'), ('NM', 'Namibia'), ('NG', 'Niger'), ('NI', 'Nigeria'), ('PY', 'Pygmy'), ('CH', 'Republic of Chad'), ('RD', 'Republic of Djibouti'), ('RE', 'Republic of Equatorial Guinea'), ('RG', 'Republic of Guinea-Bissau'), ('RS', 'Republic of Sao Tome and Principe'), ('SY', 'Republic of Seychelles'), ('RC', 'Repulic of the Congo (Congo-Brazzaville)'), ('RI', 'Reunion Island'), ('RW', 'Rwanda'), ('SE', 'Semitic'), ('SN', 'Senegal'), ('SL', 'Sierra Leone'), ('SO', 'Somalia'), ('SA', 'South Africa'), ('SS', 'South Sudan'), ('SU', 'Sudan'), ('SW', 'Swaziland'), ('TA', 'Tanzania'), ('TO', 'Togo'), ('TN', 'Tunisia'), ('UG', 'Uganda'), ('UC', 'Union of the Comoros'), ('YA', 'Yao'), ('ZA', 'Zaire'), ('ZM', 'Zambia'), ('ZI', 'Zimbabwe'), ('ZU', 'Zulu')], default='--', max_length=2)),
                ('interest', models.CharField(blank=True, choices=[('LEARN', 'Learning'), ('NETWORK', 'Network'), ('SCOUT', 'Scout players'), ('PROMOTE', 'Promote yourself'), ('OTHER', 'Other')], default='', max_length=100)),
                ('avatar', models.ImageField(blank=True, default='avatars/none/default_avatar.svg', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_flickr_content',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_flickr_heading',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_gallery_heading',
            field=models.CharField(blank=True, default='Our clients', help_text='If present and featured_gallery is selected a carousel of the gallery images will be shown with this title.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_portfolio_heading',
            field=models.CharField(blank=True, default='Recent works', help_text='If present and featured_portfolio is set portfolio items will be shown with this header.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='icon_box_layout',
            field=models.CharField(choices=[('TW', 'Two across'), ('TH', 'Three across'), ('TB', 'Three across boxes')], default='TH', max_length=2),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='max_portfolio_items',
            field=models.PositiveIntegerField(blank=True, default=6, help_text='The maximum number of items from the above selected portoflio to show.', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='recent_blog_heading',
            field=models.CharField(blank=True, default='Latest blog posts', help_text='If present recent blog posts will be shown', max_length=100),
        ),
        migrations.AlterField(
            model_name='iconbox',
            name='icon',
            field=models.CharField(help_text='Enter the name of a font awesome icon, i.e. fa-eye. A list is available here http://fontawesome.io/', max_length=50),
        ),
        migrations.AlterField(
            model_name='iconbox',
            name='link',
            field=models.CharField(blank=True, help_text='Optional, if provided clicking the box will go here.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='blog_layout',
            field=models.PositiveIntegerField(choices=[(1, 'One'), (2, 'Two')], default=2, help_text='Determines how many blog posts are shown per row in the blog list view'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='color_scheme',
            field=models.PositiveIntegerField(default=3, help_text='Use the cog icon in the front end to try out color schemes.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_iframe',
            field=models.TextField(blank=True, help_text="If present any form with slug contact will displayed with a custom template that has this iframe at the top. i.e. add a Google Map's iframe here."),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_iframe_layout',
            field=models.CharField(blank=True, choices=[('FULL', 'Full width'), ('PAGE', 'Page width')], default='FULL', max_length=4),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_blog_heading',
            field=models.CharField(default='Recent posts', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_menu_heading',
            field=models.CharField(default='Popular pages', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='sidebar_alignment',
            field=models.CharField(choices=[('LE', 'Left'), ('RI', 'Right')], default='RI', help_text='For pages that have a sidebar, determines if it is on the left or right', max_length=2),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_text',
            field=models.CharField(blank=True, help_text='Optional, if present a button with the link specified below will be in the slide', max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(blank=True, help_text='Add <br> for line breaks'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='custom',
            field=models.TextField(blank=True, help_text='Create a custom slide, everything else will be overriden'),
        ),
    ]
